import os
import json
import sys

# Markers delimiting the AIM-managed region inside generated rule files.
# Content OUTSIDE the markers is user-owned and always preserved.
AIM_BEGIN = "<!-- AIM:BEGIN (auto-generated by `aim sync` - edits inside this block will be overwritten) -->"
AIM_END = "<!-- AIM:END -->"

def find_project_root():
    # Walk up from the current directory looking for an initialized workspace.
    cwd = os.getcwd()
    current = cwd
    while True:
        if os.path.exists(os.path.join(current, ".ai-context", "config.json")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    # Fallback to the directory of this script's parent if it exists
    script_dir = os.path.dirname(os.path.abspath(__file__))
    script_parent = os.path.dirname(script_dir)
    if os.path.exists(os.path.join(script_parent, ".ai-context", "config.json")):
        return script_parent
    return cwd

def load_config(root_dir):
    config_path = os.path.join(root_dir, ".ai-context", "config.json")
    if not os.path.exists(config_path):
        print(f"[-] Configuration file not found at {config_path}")
        print("[-] Please run 'aim init' first to initialize the workspace.")
        sys.exit(1)

    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)

def write_managed_file(path, generated_content, header_if_new=None):
    """Write generated content into the AIM-managed block of `path`.

    - New file: the whole file is the managed block (optionally preceded by
      `header_if_new`, e.g. MDC frontmatter that must sit at the very top).
    - Existing file with markers: only the region between the markers is
      replaced; everything the user wrote around it is preserved.
    - Existing file without markers (pre-AIM or hand-written): the original
      is backed up to <name>.bak once, then the managed block is appended
      below the user's content - nothing is deleted.
    """
    block = f"{AIM_BEGIN}\n{generated_content.strip()}\n{AIM_END}\n"

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
        if AIM_BEGIN in existing and AIM_END in existing:
            prefix = existing.split(AIM_BEGIN, 1)[0]
            suffix = existing.split(AIM_END, 1)[1]
            new_content = prefix + block + suffix
        else:
            backup_path = path + ".bak"
            if not os.path.exists(backup_path):
                with open(backup_path, "w", encoding="utf-8") as f:
                    f.write(existing)
                print(f"[*] Existing {os.path.basename(path)} had no AIM markers; backed it up to {os.path.basename(backup_path)}.")
            new_content = existing.rstrip("\n") + "\n\n" + block
    else:
        new_content = (header_if_new or "") + block

    tmp_path = f"{path}.{os.getpid()}.tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    os.replace(tmp_path, path)

def _suite_counts():
    """Count the bundled specialist agents, skills, and workflows so the
    generated instruction files never quote a stale number. Reads the packaged
    templates relative to this module; returns (agents, skills, workflows)."""
    base = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates", "aim-agents")

    def _n(sub, ext=None):
        d = os.path.join(base, sub)
        try:
            entries = os.listdir(d)
        except OSError:
            return 0
        if ext is None:  # count sub-directories (skills are folders)
            return sum(1 for e in entries if os.path.isdir(os.path.join(d, e)))
        return sum(1 for e in entries if e.endswith(ext))

    return _n("agent", ".md"), _n("skills"), _n("workflows", ".md")


_N_AGENTS, _N_SKILLS, _N_WORKFLOWS = _suite_counts()
_SUITE_LINE = (
    f"You have access to {_N_AGENTS} specialist personas, {_N_SKILLS} skills, and "
    f"{_N_WORKFLOWS} workflows provided by AIM:"
    if (_N_AGENTS and _N_SKILLS and _N_WORKFLOWS)
    else "You have access to AIM's suite of specialist personas, skills, and workflows:"
)

SKILLS_INDEX_MD = f"""
## Modular Skills & Agent Personas (Load On-Demand to Save Tokens)
When working on specific tasks, read and load these modular rules to guide your implementation:
- **Memory & Cross-Referencing:** `.ai-context/skills/project-memory/SKILL.md` (Read when creating docs, referencing files, or managing tasks)
- **Agent Orchestration & Coordination:** `.ai-context/skills/agent-orchestration/SKILL.md` (Read when coordinating subagents, choosing specialist roles, or managing long conversation histories)
- **Token Optimization & Command Guidelines:** `.ai-context/skills/token-optimizer/SKILL.md` (Read when running shell commands, executing test suites, or doing search operations)

### Specialist Agent Suite & Workflows (.aim-agents/)
{_SUITE_LINE}
- **Specialist Personas:** `.aim-agents/agent/` (Includes `frontend-specialist.md`, `backend-specialist.md`, `database-architect.md`, `devops-engineer.md`, `security-auditor.md`, `debugger.md`, `orchestrator.md`, etc.)
- **Advanced Domain Skills:** `.aim-agents/skills/` (Includes `nextjs-react-expert/`, `web-design-guidelines/`, `api-patterns/`, `testing-patterns/`, `python-patterns/`, `database-design/`, `systematic-debugging/`, etc.)
- **Agentic Workflows:** `.aim-agents/workflows/` (Includes rules for `/brainstorm`, `/coordinate`, `/plan`, `/debug`, `/verify`, `/remember`, etc.)
"""

def generate_claude_md(config):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("claude", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    commands = config.get("commands", {})
    build_cmd = commands.get("build", "")
    test_cmd = commands.get("test", "")
    lint_cmd = commands.get("lint", "")
    format_cmd = commands.get("format", "")

    content = f"""# CLAUDE.md — Claude Code Project Guidelines

**Project Name:** {config.get("projectName", "My Project")}
**Description:** {config.get("projectDescription", "")}

## Technology Stack
{tech_stack_str}

## Core Commands
- **Build/Compile:** `{build_cmd}`
- **Run Tests:** `{test_cmd}`
- **Lint Code:** `{lint_cmd}`
- **Format Code:** `{format_cmd}`

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Claude-Specific Custom Instructions
{custom_rules_str}
{SKILLS_INDEX_MD}
---

## Token-Saving Command Optimization (RTK)
When running shell commands inside Claude Code, use the following rules to conserve token usage:
1. **Prefer targeted commands:** Avoid listing entire directories or reading massive files when specific tools or lines can be targeted.
2. **Compact Git:** Use `git status -s` or `git diff --stat` for initial context before pulling full diffs.
3. **Filter Test Output:** If tests fail, run only the failing tests rather than the entire suite if possible.
4. **Use CLI Output Wrappers:** When running commands with excessive verbose logs, pipe output or use filtering tools to return only errors or warnings.
"""
    return content

def generate_antigravity_md(config):
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("antigravity", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    content = f"""# ANTIGRAVITY.md — Antigravity Agent Guidelines

This file governs the behavior of the Antigravity agent (Google DeepMind Advanced Agentic Coding assistant) in this repository.

## Planning & Execution Flow (Planning Mode)
1. **Research & Plan**: When given complex tasks, major architectural changes, or significant decision-making:
   - Create or update the `implementation_plan.md` in the brain conversation directory.
   - Do NOT make source code changes or run modifying commands during the research phase.
   - Outline the proposed changes, verification plan, and open questions.
   - Set `request_feedback = true` in the metadata, and wait for explicit user approval.
2. **Checklist (task.md)**: Once approved, create the `task.md` file to log and track your checklist items. Update it dynamically as you work (`[/]` for in-progress, `[x]` for completed).
3. **Verify**: Ensure the changes build and all test suites pass. Run automated validation commands.
4. **Walkthrough**: Update `walkthrough.md` to summarize all changes, testing performed, and validation results.

## Knowledge Items (KI) System Rules
- **Mandatory First Step**: Always check the provided KI summaries at the start of each conversation.
- **Reference KIs**: Read relevant KI artifacts in `<appDataDir>\\knowledge` BEFORE doing independent research or writing code.
- **Verify against active code**: Cross-reference KI patterns with current code to avoid using stale patterns or APIs.

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Antigravity-Specific Rules
{custom_rules_str}
{SKILLS_INDEX_MD}
"""
    return content

def generate_cursorrules(config):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("codex", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    content = f"""# Cursor Rules & Coding Standards

**Project Name:** {config.get("projectName", "My Project")}

## Tech Stack
{tech_stack_str}

## Coding Conventions
{conventions_str}

## Project Constraints
{constraints_str}

## Codex/Cursor Custom Rules
{custom_rules_str}

## UI & Design Rules (if building UI)
- **Rich Aesthetics**: Avoid browser default components. Use sleek modern palettes, clear typography (Inter, Outfit, Roboto), and rounded corners.
- **No Placeholders**: Never leave empty placeholders or TODOs in visual layouts. Use actual working logic or assets.
- **Micro-animations**: Implement smooth transitions and hover micro-animations to enhance user experience.
- **Responsive Layout**: Always verify that the layout adapts elegantly to different viewport sizes.
{SKILLS_INDEX_MD}
"""
    return content

def generate_copilot_instructions(config):
    tech_stack_str = ", ".join(config.get("techStack", []))
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    content = f"""# GitHub Copilot Instructions

## Project Context
This is the '{config.get("projectName", "My Project")}' project.
Description: {config.get("projectDescription", "")}
Technology Stack: {tech_stack_str}

## Coding Conventions
{conventions_str}

## Constraints & Requirements
{constraints_str}
{SKILLS_INDEX_MD}
"""
    return content

def generate_agents_md(config):
    """AGENTS.md - the cross-tool agent instructions convention adopted by
    OpenAI Codex, Cursor, Google Jules, and others."""
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    commands = config.get("commands", {})

    content = f"""# AGENTS.md

Instructions for AI coding agents working in this repository.

## Project
**{config.get("projectName", "My Project")}** - {config.get("projectDescription", "")}

## Tech Stack
{tech_stack_str}

## Commands
- Build: `{commands.get("build", "")}`
- Test: `{commands.get("test", "")}`
- Lint: `{commands.get("lint", "")}`
- Format: `{commands.get("format", "")}`

Run the test and lint commands before declaring a change complete.

## Code Style & Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}
{SKILLS_INDEX_MD}"""
    return content


def generate_gemini_md(config):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    custom_rules = config.get("customRules", {}).get("gemini", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    commands = config.get("commands", {})

    content = f"""# GEMINI.md — Gemini CLI / Code Assist Project Guidelines

**Project Name:** {config.get("projectName", "My Project")}
**Description:** {config.get("projectDescription", "")}

## Technology Stack
{tech_stack_str}

## Core Commands
- **Build/Compile:** `{commands.get("build", "")}`
- **Run Tests:** `{commands.get("test", "")}`
- **Lint Code:** `{commands.get("lint", "")}`
- **Format Code:** `{commands.get("format", "")}`

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Gemini-Specific Custom Instructions
{custom_rules_str}
{SKILLS_INDEX_MD}"""
    return content


def generate_cursor_mdc(config):
    """Body of .cursor/rules/aim.mdc - Cursor's current project-rules format
    (the legacy .cursorrules file is deprecated but still emitted for
    backwards compatibility)."""
    return generate_cursorrules(config)


# Frontmatter that must sit at the very top of a brand-new .mdc file for
# Cursor to parse it. On re-sync it lives outside the AIM markers and is
# preserved (and user-editable) like any other user content.
CURSOR_MDC_FRONTMATTER = """---
description: AIM project rules and coding conventions
alwaysApply: true
---

"""

# Single source of truth for every sync target. Each entry is
# (label, relative path, generator). cmd_status consumes this list too,
# so the status report can never drift from what sync actually writes.
SYNC_TARGETS = [
    ("CLAUDE.md", "CLAUDE.md", generate_claude_md),
    ("AGENTS.md", "AGENTS.md", generate_agents_md),
    ("GEMINI.md", "GEMINI.md", generate_gemini_md),
    ("ANTIGRAVITY.md", "ANTIGRAVITY.md", generate_antigravity_md),
    (".cursor/rules/aim.mdc", os.path.join(".cursor", "rules", "aim.mdc"), generate_cursor_mdc),
    (".cursorrules", ".cursorrules", generate_cursorrules),
    (".windsurfrules", ".windsurfrules", generate_cursorrules),
    ("copilot-instructions.md", os.path.join(".github", "copilot-instructions.md"), generate_copilot_instructions),
]

# Per-target header prepended when the file is created for the first time.
NEW_FILE_HEADERS = {
    os.path.join(".cursor", "rules", "aim.mdc"): CURSOR_MDC_FRONTMATTER,
}


def imported_rules_section(root_dir):
    """Concatenate rules collected by `aim ingest` (.ai-context/imported/*.md)
    into one markdown section, re-emitted into every client file so scattered
    rules become a single consolidated source of truth. Returns '' if none."""
    imported_dir = os.path.join(root_dir, ".ai-context", "imported")
    if not os.path.isdir(imported_dir):
        return ""
    blocks = []
    for name in sorted(os.listdir(imported_dir)):
        if name.endswith(".md"):
            try:
                with open(os.path.join(imported_dir, name), "r", encoding="utf-8") as f:
                    body = f.read().strip()
            except OSError:
                continue
            if body:
                blocks.append(body)
    if not blocks:
        return ""
    return "\n\n## Imported Project Rules\n\n" + "\n\n".join(blocks) + "\n"


def main():
    root_dir = find_project_root()
    print(f"[*] Detected project root: {root_dir}")

    config = load_config(root_dir)
    print("[*] Loaded configuration file successfully.")

    imported = imported_rules_section(root_dir)

    for label, rel_path, generator in SYNC_TARGETS:
        target_path = os.path.join(root_dir, rel_path)
        parent_dir = os.path.dirname(target_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir)
        write_managed_file(target_path, generator(config) + imported,
                           header_if_new=NEW_FILE_HEADERS.get(rel_path))
        print(f"[+] Synchronized {target_path}")

    print("[+] Synchronization completed successfully!")

if __name__ == "__main__":
    main()
