import os
import json
import sys

# Markers delimiting the AIM-managed region inside generated rule files.
# Content OUTSIDE the markers is user-owned and always preserved.
AIM_BEGIN = "<!-- AIM:BEGIN (auto-generated by `aim sync` - edits inside this block will be overwritten) -->"
AIM_END = "<!-- AIM:END -->"

def find_project_root():
    # Walk up from the current directory looking for an initialized workspace.
    cwd = os.getcwd()
    current = cwd
    while True:
        if os.path.exists(os.path.join(current, ".ai-context", "config.json")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    # Fallback to the directory of this script's parent if it exists
    script_dir = os.path.dirname(os.path.abspath(__file__))
    script_parent = os.path.dirname(script_dir)
    if os.path.exists(os.path.join(script_parent, ".ai-context", "config.json")):
        return script_parent
    return cwd

def load_config(root_dir):
    config_path = os.path.join(root_dir, ".ai-context", "config.json")
    if not os.path.exists(config_path):
        print(f"[-] Configuration file not found at {config_path}")
        print("[-] Please run 'aim init' first to initialize the workspace.")
        sys.exit(1)

    with open(config_path, "r", encoding="utf-8") as f:
        return json.load(f)

def write_managed_file(path, generated_content, header_if_new=None):
    """Write generated content into the AIM-managed block of `path`.

    - New file: the whole file is the managed block (optionally preceded by
      `header_if_new`, e.g. MDC frontmatter that must sit at the very top).
    - Existing file with markers: only the region between the markers is
      replaced; everything the user wrote around it is preserved.
    - Existing file without markers (pre-AIM or hand-written): the original
      is backed up to <name>.bak once, then the managed block is appended
      below the user's content - nothing is deleted.
    """
    block = f"{AIM_BEGIN}\n{generated_content.strip()}\n{AIM_END}\n"

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            existing = f.read()
        if AIM_BEGIN in existing and AIM_END in existing:
            prefix = existing.split(AIM_BEGIN, 1)[0]
            suffix = existing.split(AIM_END, 1)[1]
            new_content = prefix + block + suffix
        else:
            backup_path = path + ".bak"
            if not os.path.exists(backup_path):
                with open(backup_path, "w", encoding="utf-8") as f:
                    f.write(existing)
                print(f"[*] Existing {os.path.basename(path)} had no AIM markers; backed it up to {os.path.basename(backup_path)}.")
            new_content = existing.rstrip("\n") + "\n\n" + block
    else:
        new_content = (header_if_new or "") + block

    tmp_path = f"{path}.{os.getpid()}.tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        f.write(new_content)
    os.replace(tmp_path, path)

def _suite_counts():
    """Count the bundled specialist agents, skills, and workflows so the
    generated instruction files never quote a stale number. Reads the packaged
    templates relative to this module; returns (agents, skills, workflows)."""
    base = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates", "aim-agents")

    def _n(sub, ext=None):
        d = os.path.join(base, sub)
        try:
            entries = os.listdir(d)
        except OSError:
            return 0
        if ext is None:  # count sub-directories (skills are folders)
            return sum(1 for e in entries if os.path.isdir(os.path.join(d, e)))
        return sum(1 for e in entries if e.endswith(ext))

    return _n("agent", ".md"), _n("skills"), _n("workflows", ".md")


_N_AGENTS, _N_SKILLS, _N_WORKFLOWS = _suite_counts()
_SUITE_LINE = (
    f"You have access to {_N_AGENTS} specialist personas, {_N_SKILLS} skills, and "
    f"{_N_WORKFLOWS} workflows provided by AIM:"
    if (_N_AGENTS and _N_SKILLS and _N_WORKFLOWS)
    else "You have access to AIM's suite of specialist personas, skills, and workflows:"
)

def _p(root_dir, rel_path):
    """Return an absolute path when root_dir is known, else the original relative path.
    Uses forward slashes for cross-platform agent readability."""
    if root_dir:
        return os.path.join(root_dir, rel_path).replace("\\", "/")
    return rel_path


def skills_index_md(root_dir=None):
    """Generate the skills index section with absolute paths when root_dir is provided."""
    ctx = _p(root_dir, ".ai-context/skills/project-memory/SKILL.md")
    orc = _p(root_dir, ".ai-context/skills/agent-orchestration/SKILL.md")
    tok = _p(root_dir, ".ai-context/skills/token-optimizer/SKILL.md")
    agents = _p(root_dir, ".aim-agents/agent/")
    skills = _p(root_dir, ".aim-agents/skills/")
    wflows = _p(root_dir, ".aim-agents/workflows/")

    return f"""
## Modular Skills & Agent Personas (Load On-Demand to Save Tokens)
When working on specific tasks, read and load these modular rules to guide your implementation:
- **Memory & Cross-Referencing:** `{ctx}` (Read when creating docs, referencing files, or managing tasks)
- **Agent Orchestration & Coordination:** `{orc}` (Read when coordinating subagents, choosing specialist roles, or managing long conversation histories)
- **Token Optimization & Command Guidelines:** `{tok}` (Read when running shell commands, executing test suites, or doing search operations)

### Specialist Agent Suite & Workflows (.aim-agents/)
{_SUITE_LINE}
- **Specialist Personas:** `{agents}` (Includes `frontend-specialist.md`, `backend-specialist.md`, `database-architect.md`, `devops-engineer.md`, `security-auditor.md`, `debugger.md`, `orchestrator.md`, etc.)
- **Advanced Domain Skills:** `{skills}` (Includes `nextjs-react-expert/`, `web-design-guidelines/`, `api-patterns/`, `testing-patterns/`, `python-patterns/`, `database-design/`, `systematic-debugging/`, etc.)
- **Agentic Workflows:** `{wflows}` (Includes rules for `/brainstorm`, `/coordinate`, `/plan`, `/debug`, `/verify`, `/remember`, etc.)
"""


# Backward compatibility: keep the module-level constant for any external callers.
SKILLS_INDEX_MD = skills_index_md()

def generate_claude_md(config, root_dir=None):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("claude", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    commands = config.get("commands", {})
    build_cmd = commands.get("build", "")
    test_cmd = commands.get("test", "")
    lint_cmd = commands.get("lint", "")
    format_cmd = commands.get("format", "")

    content = f"""# CLAUDE.md — Claude Code Project Guidelines

**Project Name:** {config.get("projectName", "My Project")}
**Description:** {config.get("projectDescription", "")}

## Technology Stack
{tech_stack_str}

## Core Commands
- **Build/Compile:** `{build_cmd}`
- **Run Tests:** `{test_cmd}`
- **Lint Code:** `{lint_cmd}`
- **Format Code:** `{format_cmd}`

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Claude-Specific Custom Instructions
{custom_rules_str}
{skills_index_md(root_dir)}
---

## Token-Saving Command Optimization (RTK)
When running shell commands inside Claude Code, use the following rules to conserve token usage:
1. **Prefer targeted commands:** Avoid listing entire directories or reading massive files when specific tools or lines can be targeted.
2. **Compact Git:** Use `git status -s` or `git diff --stat` for initial context before pulling full diffs.
3. **Filter Test Output:** If tests fail, run only the failing tests rather than the entire suite if possible.
4. **Use CLI Output Wrappers:** When running commands with excessive verbose logs, pipe output or use filtering tools to return only errors or warnings.
"""
    return content

def generate_antigravity_md(config, root_dir=None):
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("antigravity", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    content = f"""# ANTIGRAVITY.md — Antigravity Agent Guidelines

This file governs the behavior of the Antigravity agent (Google DeepMind Advanced Agentic Coding assistant) in this repository.

## Planning & Execution Flow (Planning Mode)
1. **Research & Plan**: When given complex tasks, major architectural changes, or significant decision-making:
   - Create or update the `implementation_plan.md` in the brain conversation directory.
   - Do NOT make source code changes or run modifying commands during the research phase.
   - Outline the proposed changes, verification plan, and open questions.
   - Set `request_feedback = true` in the metadata, and wait for explicit user approval.
2. **Checklist (task.md)**: Once approved, create the `task.md` file to log and track your checklist items. Update it dynamically as you work (`[/]` for in-progress, `[x]` for completed).
3. **Verify**: Ensure the changes build and all test suites pass. Run automated validation commands.
4. **Walkthrough**: Update `walkthrough.md` to summarize all changes, testing performed, and validation results.

## Knowledge Items (KI) System Rules
- **Mandatory First Step**: Always check the provided KI summaries at the start of each conversation.
- **Reference KIs**: Read relevant KI artifacts in `<appDataDir>\\knowledge` BEFORE doing independent research or writing code.
- **Verify against active code**: Cross-reference KI patterns with current code to avoid using stale patterns or APIs.

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Antigravity-Specific Rules
{custom_rules_str}
{skills_index_md(root_dir)}
"""
    return content

def generate_cursorrules(config, root_dir=None):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])
    
    custom_rules = config.get("customRules", {}).get("codex", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    content = f"""# Cursor Rules & Coding Standards

**Project Name:** {config.get("projectName", "My Project")}

## Tech Stack
{tech_stack_str}

## Coding Conventions
{conventions_str}

## Project Constraints
{constraints_str}

## Codex/Cursor Custom Rules
{custom_rules_str}

## UI & Design Rules (if building UI)
- **Rich Aesthetics**: Avoid browser default components. Use sleek modern palettes, clear typography (Inter, Outfit, Roboto), and rounded corners.
- **No Placeholders**: Never leave empty placeholders or TODOs in visual layouts. Use actual working logic or assets.
- **Micro-animations**: Implement smooth transitions and hover micro-animations to enhance user experience.
- **Responsive Layout**: Always verify that the layout adapts elegantly to different viewport sizes.
{skills_index_md(root_dir)}
"""
    return content

def generate_copilot_instructions(config, root_dir=None):
    tech_stack_str = ", ".join(config.get("techStack", []))
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    content = f"""# GitHub Copilot Instructions

## Project Context
This is the '{config.get("projectName", "My Project")}' project.
Description: {config.get("projectDescription", "")}
Technology Stack: {tech_stack_str}

## Coding Conventions
{conventions_str}

## Constraints & Requirements
{constraints_str}
{skills_index_md(root_dir)}
"""
    return content

def generate_agents_md(config, root_dir=None):
    """AGENTS.md - the cross-tool agent instructions convention adopted by
    OpenAI Codex, Cursor, Google Jules, and others."""
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    commands = config.get("commands", {})

    content = f"""# AGENTS.md

Instructions for AI coding agents working in this repository.

## Project
**{config.get("projectName", "My Project")}** - {config.get("projectDescription", "")}

## Tech Stack
{tech_stack_str}

## Commands
- Build: `{commands.get("build", "")}`
- Test: `{commands.get("test", "")}`
- Lint: `{commands.get("lint", "")}`
- Format: `{commands.get("format", "")}`

Run the test and lint commands before declaring a change complete.

## Code Style & Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}
{skills_index_md(root_dir)}"""
    return content


def generate_gemini_md(config, root_dir=None):
    tech_stack_str = "\n".join([f"- {item}" for item in config.get("techStack", [])])
    conventions_str = "\n".join([f"- {item}" for item in config.get("conventions", [])])
    constraints_str = "\n".join([f"- {item}" for item in config.get("constraints", [])])

    custom_rules = config.get("customRules", {}).get("gemini", [])
    custom_rules_str = "\n".join([f"- {item}" for item in custom_rules]) if custom_rules else "- Follow standard programming practices."

    commands = config.get("commands", {})

    content = f"""# GEMINI.md — Gemini CLI / Code Assist Project Guidelines

**Project Name:** {config.get("projectName", "My Project")}
**Description:** {config.get("projectDescription", "")}

## Technology Stack
{tech_stack_str}

## Core Commands
- **Build/Compile:** `{commands.get("build", "")}`
- **Run Tests:** `{commands.get("test", "")}`
- **Lint Code:** `{commands.get("lint", "")}`
- **Format Code:** `{commands.get("format", "")}`

## Coding Conventions
{conventions_str}

## Constraints & Safety Rules
{constraints_str}

## Gemini-Specific Custom Instructions
{custom_rules_str}
{skills_index_md(root_dir)}"""
    return content


def generate_cursor_mdc(config, root_dir=None):
    """Body of .cursor/rules/aim.mdc - Cursor's current project-rules format
    (the legacy .cursorrules file is deprecated but still emitted for
    backwards compatibility)."""
    return generate_cursorrules(config, root_dir)


# Frontmatter that must sit at the very top of a brand-new .mdc file for
# Cursor to parse it. On re-sync it lives outside the AIM markers and is
# preserved (and user-editable) like any other user content.
CURSOR_MDC_FRONTMATTER = """---
description: AIM project rules and coding conventions
alwaysApply: true
---

"""

# Single source of truth for every sync target. Each entry is
# (label, relative path, generator). cmd_status consumes this list too,
# so the status report can never drift from what sync actually writes.
SYNC_TARGETS = [
    ("CLAUDE.md", "CLAUDE.md", generate_claude_md),
    ("AGENTS.md", "AGENTS.md", generate_agents_md),
    ("GEMINI.md", "GEMINI.md", generate_gemini_md),
    ("ANTIGRAVITY.md", "ANTIGRAVITY.md", generate_antigravity_md),
    (".cursor/rules/aim.mdc", os.path.join(".cursor", "rules", "aim.mdc"), generate_cursor_mdc),
    (".cursorrules", ".cursorrules", generate_cursorrules),
    (".windsurfrules", ".windsurfrules", generate_cursorrules),
    ("copilot-instructions.md", os.path.join(".github", "copilot-instructions.md"), generate_copilot_instructions),
]

# Maps each sync target's relative path to the agent key in config.json.
# Used to skip targets whose agent is disabled.
TARGET_AGENT_MAP = {
    "CLAUDE.md": "claude",
    "AGENTS.md": "codex",
    "GEMINI.md": "gemini",
    "ANTIGRAVITY.md": "antigravity",
    os.path.join(".cursor", "rules", "aim.mdc"): "cursor",
    ".cursorrules": "cursor",
    ".windsurfrules": "windsurf",
    os.path.join(".github", "copilot-instructions.md"): "copilot",
}

# Per-target header prepended when the file is created for the first time.
NEW_FILE_HEADERS = {
    os.path.join(".cursor", "rules", "aim.mdc"): CURSOR_MDC_FRONTMATTER,
}


def imported_rules_section(root_dir):
    """Concatenate rules collected by `aim ingest` (.ai-context/imported/*.md)
    into one markdown section, re-emitted into every client file so scattered
    rules become a single consolidated source of truth. Returns '' if none."""
    imported_dir = os.path.join(root_dir, ".ai-context", "imported")
    if not os.path.isdir(imported_dir):
        return ""
    blocks = []
    for name in sorted(os.listdir(imported_dir)):
        if name.endswith(".md"):
            try:
                with open(os.path.join(imported_dir, name), "r", encoding="utf-8") as f:
                    body = f.read().strip()
            except OSError:
                continue
            if body:
                blocks.append(body)
    if not blocks:
        return ""
    return "\n\n## Imported Project Rules\n\n" + "\n\n".join(blocks) + "\n"

def _parse_skill_frontmatter(path):
    """Parse YAML-like frontmatter from a SKILL.md or agent .md file.
    Returns dict with 'name' and 'description' (or empty dict on failure)."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except OSError:
        return {}
    if not content.startswith("---"):
        return {}
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}
    fm = {}
    for line in parts[1].strip().splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip()
    return fm


def _collect_skills(root_dir):
    """Collect all skills, agent personas, and workflows from project.
    Returns list of dicts: {type, name, description, rel_path}."""
    items = []

    # 1. Domain skills (.aim-agents/skills/<name>/SKILL.md)
    skills_dir = os.path.join(root_dir, ".aim-agents", "skills")
    if os.path.isdir(skills_dir):
        for name in sorted(os.listdir(skills_dir)):
            skill_file = os.path.join(skills_dir, name, "SKILL.md")
            if os.path.isfile(skill_file):
                fm = _parse_skill_frontmatter(skill_file)
                desc = fm.get("description", f"AIM skill: {name}")
                items.append({
                    "type": "skill",
                    "name": name,
                    "command_name": f"aim-{name}",
                    "description": desc,
                    "rel_path": f".aim-agents/skills/{name}/SKILL.md",
                })

    # 2. Core skills (.ai-context/skills/<name>/SKILL.md)
    core_dir = os.path.join(root_dir, ".ai-context", "skills")
    if os.path.isdir(core_dir):
        for name in sorted(os.listdir(core_dir)):
            skill_file = os.path.join(core_dir, name, "SKILL.md")
            if os.path.isfile(skill_file):
                fm = _parse_skill_frontmatter(skill_file)
                desc = fm.get("description", f"AIM core skill: {name}")
                items.append({
                    "type": "skill",
                    "name": name,
                    "command_name": f"aim-{name}",
                    "description": desc,
                    "rel_path": f".ai-context/skills/{name}/SKILL.md",
                })

    # 3. Agent personas (.aim-agents/agent/<name>.md)
    agent_dir = os.path.join(root_dir, ".aim-agents", "agent")
    if os.path.isdir(agent_dir):
        for fname in sorted(os.listdir(agent_dir)):
            if fname.endswith(".md"):
                agent_name = fname[:-3]
                agent_file = os.path.join(agent_dir, fname)
                fm = _parse_skill_frontmatter(agent_file)
                desc = fm.get("description", f"AIM agent persona: {agent_name}")
                items.append({
                    "type": "agent",
                    "name": agent_name,
                    "command_name": f"aim-agent-{agent_name}",
                    "description": desc,
                    "rel_path": f".aim-agents/agent/{fname}",
                })

    # 4. Workflows (.aim-agents/workflows/<name>.md)
    wf_dir = os.path.join(root_dir, ".aim-agents", "workflows")
    if os.path.isdir(wf_dir):
        for fname in sorted(os.listdir(wf_dir)):
            if fname.endswith(".md"):
                wf_name = fname[:-3]
                wf_file = os.path.join(wf_dir, fname)
                fm = _parse_skill_frontmatter(wf_file)
                desc = fm.get("description", f"AIM workflow: {wf_name}")
                items.append({
                    "type": "workflow",
                    "name": wf_name,
                    "command_name": f"aim-workflow-{wf_name}",
                    "description": desc,
                    "rel_path": f".aim-agents/workflows/{fname}",
                })

    return items


def _truncate(text, max_len=200):
    """Truncate text to max_len characters for frontmatter descriptions."""
    if len(text) <= max_len:
        return text
    return text[:max_len - 3] + "..."


def generate_skill_commands(root_dir, enabled_agents=None):
    """Generate /aim-<skill> slash command files for all supported platforms.

    If enabled_agents is provided, only generate for enabled platforms.

    Platforms:
    - Claude Code:   .claude/commands/aim-*.md
    - Cursor:        .cursor/rules/aim-*.mdc
    - Windsurf:      .windsurf/rules/aim-*.md
    - Antigravity:   ~/.gemini/config/plugins/aim-skills/skills/aim-*.md
    """
    items = _collect_skills(root_dir)
    if not items:
        return 0

    abs_root = root_dir.replace("\\", "/")
    counts = {"claude": 0, "cursor": 0, "windsurf": 0, "antigravity": 0}
    if enabled_agents is None:
        enabled_agents = {"claude": True, "cursor": True,
                          "windsurf": True, "antigravity": True}

    def _write_all(out_dir, ext, make_content, key):
        os.makedirs(out_dir, exist_ok=True)
        for item in items:
            path = os.path.join(out_dir, f"{item['command_name']}{ext}")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(make_content(item))
            counts[key] += 1

    # ---- Claude Code ----
    if enabled_agents.get("claude", True):
        def _claude(it):
            return (f'---\ndescription: "{_truncate(it["description"])}"\n---\n\n'
                    f'Read and strictly follow the instructions from the file:\n'
                    f'`{abs_root}/{it["rel_path"]}`\n\n'
                    f'If the skill references additional sub-files '
                    f'(e.g. in a file index table), read those relevant files too.\n\n'
                    f'Apply the skill\'s guidelines to complete this task:\n\n'
                    f'$ARGUMENTS\n')
        _write_all(os.path.join(root_dir, ".claude", "commands"),
                   ".md", _claude, "claude")

    # ---- Cursor ----
    if enabled_agents.get("cursor", True):
        def _cursor(it):
            return (f'---\ndescription: "{_truncate(it["description"])}"\n'
                    f'alwaysApply: false\n---\n\n'
                    f'Read and strictly follow the instructions from the file:\n'
                    f'`{abs_root}/{it["rel_path"]}`\n\n'
                    f'If the skill references additional sub-files '
                    f'(e.g. in a file index table), read those relevant files too.\n\n'
                    f'Apply the skill\'s guidelines to the current task.\n')
        _write_all(os.path.join(root_dir, ".cursor", "rules"),
                   ".mdc", _cursor, "cursor")

    # ---- Windsurf ----
    if enabled_agents.get("windsurf", True):
        def _windsurf(it):
            return (f'---\ntrigger: manual\n'
                    f'description: "{_truncate(it["description"])}"\n---\n\n'
                    f'Read and strictly follow the instructions from the file:\n'
                    f'`{abs_root}/{it["rel_path"]}`\n\n'
                    f'If the skill references additional sub-files '
                    f'(e.g. in a file index table), read those relevant files too.\n\n'
                    f'Apply the skill\'s guidelines to the current task.\n')
        _write_all(os.path.join(root_dir, ".windsurf", "rules"),
                   ".md", _windsurf, "windsurf")

    # ---- Antigravity ----
    if enabled_agents.get("antigravity", True):
        home = os.path.expanduser("~")
        ag_dir = os.path.join(home, ".gemini", "config", "plugins", "aim-skills")
        sk_dir = os.path.join(ag_dir, "skills")
        os.makedirs(sk_dir, exist_ok=True)
        
        # Clean up legacy .md files in sk_dir
        if os.path.exists(sk_dir):
            for f in os.listdir(sk_dir):
                f_path = os.path.join(sk_dir, f)
                if os.path.isfile(f_path) and f.endswith(".md"):
                    try:
                        os.remove(f_path)
                    except Exception:
                        pass

        with open(os.path.join(ag_dir, "plugin.json"), "w", encoding="utf-8") as fh:
            json.dump({"name": "aim-skills", "version": "1.0.0",
                       "description": "AIM specialist skills, agent personas, and workflows.",
                       "author": {"name": "AIM CLI"}}, fh, indent=2)
        _labels = {"skill": "Skill", "agent": "Agent Persona", "workflow": "Workflow"}

        for item in items:
            skill_name = item["command_name"]  # e.g., 'aim-api-patterns'
            skill_subdir = os.path.join(sk_dir, skill_name)
            os.makedirs(skill_subdir, exist_ok=True)
            
            lbl = _labels.get(item["type"], "Skill")
            desc_clean = item["description"].replace('"', '\\"').replace('\n', ' ')
            
            content = (f'---\n'
                       f'name: {skill_name}\n'
                       f'description: "{desc_clean}"\n'
                       f'---\n\n'
                       f'# AIM {lbl}: {item["name"]}\n\n'
                       f'{item["description"]}\n\n'
                       f'## Instructions\n\n'
                       f'Read and strictly follow the full skill instructions from:\n'
                       f'`{abs_root}/{item["rel_path"]}`\n\n'
                       f'If the skill references additional sub-files '
                       f'(e.g. in a file index table), read those relevant files too.\n\n'
                       f'Apply the skill\'s guidelines to complete the user\'s task.\n')
                       
            path = os.path.join(skill_subdir, "SKILL.md")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(content)
            counts["antigravity"] += 1

    return counts


# ---------------------------------------------------------------------------
# .gitignore management
# ---------------------------------------------------------------------------

# Files that aim sync generates, grouped for gitignore management.
_GITIGNORE_RULES = [
    "CLAUDE.md", "ANTIGRAVITY.md", "GEMINI.md", "AGENTS.md",
    ".cursorrules", ".windsurfrules",
    ".github/copilot-instructions.md",
]
_GITIGNORE_COMMANDS = [
    ".claude/commands/aim-*",
    ".cursor/rules/aim-*",
    ".windsurf/rules/aim-*",
]

_GITIGNORE_MARKER_BEGIN = "# AIM generated (managed by `aim sync` — do not edit this block)"
_GITIGNORE_MARKER_END = "# /AIM"


def manage_gitignore(root_dir, strategy="track-all", enabled_agents=None):
    """Add or remove AIM entries from .gitignore based on strategy.

    Strategies:
    - track-all:  remove AIM entries from .gitignore (commit everything)
    - ignore-all: add all AIM-generated files to .gitignore
    - rules-only: track rule files, ignore slash commands
    """
    gi_path = os.path.join(root_dir, ".gitignore")

    # Build the set of entries to ignore
    entries = []
    if strategy == "ignore-all":
        entries = _GITIGNORE_RULES + _GITIGNORE_COMMANDS
    elif strategy == "rules-only":
        entries = _GITIGNORE_COMMANDS  # only ignore slash commands

    # Read existing .gitignore
    existing = ""
    if os.path.exists(gi_path):
        with open(gi_path, "r", encoding="utf-8") as f:
            existing = f.read()

    # Remove old AIM block if present
    if _GITIGNORE_MARKER_BEGIN in existing:
        before = existing.split(_GITIGNORE_MARKER_BEGIN, 1)[0]
        after_parts = existing.split(_GITIGNORE_MARKER_END, 1)
        after = after_parts[1] if len(after_parts) > 1 else ""
        existing = before.rstrip("\n") + after.lstrip("\n")

    # Add new block if there are entries
    if entries:
        block = (f"\n{_GITIGNORE_MARKER_BEGIN}\n"
                 + "\n".join(entries)
                 + f"\n{_GITIGNORE_MARKER_END}\n")
        new_content = existing.rstrip("\n") + "\n" + block
    else:
        new_content = existing

    with open(gi_path, "w", encoding="utf-8") as f:
        f.write(new_content)


def main():
    root_dir = find_project_root()
    print(f"[*] Detected project root: {root_dir}")

    config = load_config(root_dir)
    print("[*] Loaded configuration file successfully.")

    enabled_agents = config.get("agents", {})
    imported = imported_rules_section(root_dir)

    for label, rel_path, generator in SYNC_TARGETS:
        agent_key = TARGET_AGENT_MAP.get(rel_path)
        if agent_key and not enabled_agents.get(agent_key, True):
            print(f"[ ] Skipped {label} (agent '{agent_key}' disabled)")
            continue
        target_path = os.path.join(root_dir, rel_path)
        parent_dir = os.path.dirname(target_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir)
        write_managed_file(target_path, generator(config, root_dir) + imported,
                           header_if_new=NEW_FILE_HEADERS.get(rel_path))
        print(f"[+] Synchronized {target_path}")

    if config.get("skillCommands", True):
        counts = generate_skill_commands(root_dir, enabled_agents)
        if counts:
            total = sum(counts.values())
            parts = [f"{k.title()}: {v}" for k, v in counts.items() if v > 0]
            print(f"[+] Generated {total} slash commands ({', '.join(parts)})")
    else:
        print("[ ] Skill commands disabled in config")

    # Manage .gitignore
    git_strategy = config.get("gitTracking", "track-all")
    if git_strategy != "track-all":
        manage_gitignore(root_dir, git_strategy, enabled_agents)
        print(f"[+] Updated .gitignore (strategy: {git_strategy})")

    print("[+] Synchronization completed successfully!")

if __name__ == "__main__":
    main()

